spring:
  shardingsphere:
    datasource:
      ds:
        driverClassName: com.mysql.cj.jdbc.Driver
        jdbcUrl: jdbc:mysql://localhost:3306/demo_ds?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=UTF-8
        type: com.zaxxer.hikari.HikariDataSource
        username: root
        password: root
      shadow-ds:
        driverClassName: com.mysql.cj.jdbc.Driver
        jdbcUrl: jdbc:mysql://localhost:3306/shadow_demo_ds?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=UTF-8
        type: com.zaxxer.hikari.HikariDataSource
        username: root
        password: root
      names: ds,shadow-ds
    rules:
      sql-parser:
        sql-comment-parse-enabled: true
      shadow:
        data-sources:
          shadow-data-source:
            source-data-source-name: ds
            shadow-data-source-name: shadow-ds
        shadow-algorithms:
#          simple-hint-algorithm:
#            props:
#              foo: bar
#              shadow: true
#            type: SIMPLE_HINT
          user-id-delete-match-algorithm:
            props:
              column: user_id
              operation: delete
              value: 1
            type: VALUE_MATCH
          user-id-insert-match-algorithm:
            props:
              column: user_id
              operation: insert
              value: 1
            type: VALUE_MATCH
          user-id-select-match-algorithm:
            props:
              column: user_id
              operation: select
              value: 1
            type: VALUE_MATCH
        tables:
          t_user:
            data-source-names: shadow-data-source
            shadow-algorithm-names: user-id-insert-match-algorithm,user-id-delete-match-algorithm,user-id-select-match-algorithm,simple-hint-algorithm
    props:
      sql-show: true
      sql-simple: true
